Algoritmo "L05J"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : apresente os valores de conversão de graus Celsius em Fahrenheit, de
10 // em 10 graus.
// Autor(a)    : Ana Rodrigues
// Data atual  : 03/04/2024
Var
   // Seção de Declarações das variáveis
      farenheit, celsius: real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...




Fimalgoritmo